/**
 * SDK Control Types — inferred from controlSchemas.ts Zod schemas.
 *
 * This file would normally be auto-generated by `bun scripts/generate-sdk-types.ts`.
 * Since the generator script is not available, these types are manually reconstructed
 * from the schema definitions and usage sites.
 */

import type { z } from 'zod/v4'
import type {
  SDKControlInitializeRequestSchema,
  SDKControlInitializeResponseSchema,
  SDKControlInterruptRequestSchema,
  SDKControlPermissionRequestSchema,
  SDKControlSetPermissionModeRequestSchema,
  SDKControlSetModelRequestSchema,
  SDKControlSetMaxThinkingTokensRequestSchema,
  SDKControlMcpStatusRequestSchema,
  SDKControlMcpStatusResponseSchema,
  SDKControlGetContextUsageRequestSchema,
  SDKControlMcpSetServersRequestSchema,
  SDKControlMcpSetServersResponseSchema,
  SDKControlReloadPluginsRequestSchema,
  SDKControlReloadPluginsResponseSchema,
  SDKControlRequestSchema,
  SDKControlResponseSchema,
} from './controlSchemas.js'

// Re-export inferred types from control schemas
export type SDKControlInitializeRequest = z.infer<ReturnType<typeof SDKControlInitializeRequestSchema>>
export type SDKControlInitializeResponse = z.infer<ReturnType<typeof SDKControlInitializeResponseSchema>>
export type SDKControlInterruptRequest = z.infer<ReturnType<typeof SDKControlInterruptRequestSchema>>
export type SDKControlPermissionRequest = z.infer<ReturnType<typeof SDKControlPermissionRequestSchema>>
export type SDKControlSetPermissionModeRequest = z.infer<ReturnType<typeof SDKControlSetPermissionModeRequestSchema>>
export type SDKControlSetModelRequest = z.infer<ReturnType<typeof SDKControlSetModelRequestSchema>>
export type SDKControlSetMaxThinkingTokensRequest = z.infer<ReturnType<typeof SDKControlSetMaxThinkingTokensRequestSchema>>
export type SDKControlMcpStatusRequest = z.infer<ReturnType<typeof SDKControlMcpStatusRequestSchema>>
export type SDKControlMcpStatusResponse = z.infer<ReturnType<typeof SDKControlMcpStatusResponseSchema>>
export type SDKControlGetContextUsageRequest = z.infer<ReturnType<typeof SDKControlGetContextUsageRequestSchema>>
export type SDKControlMcpSetServersRequest = z.infer<ReturnType<typeof SDKControlMcpSetServersRequestSchema>>
export type SDKControlMcpSetServersResponse = z.infer<ReturnType<typeof SDKControlMcpSetServersResponseSchema>>
export type SDKControlReloadPluginsRequest = z.infer<ReturnType<typeof SDKControlReloadPluginsRequestSchema>>
export type SDKControlReloadPluginsResponse = z.infer<ReturnType<typeof SDKControlReloadPluginsResponseSchema>>

// Inner union of all control request payload types (without wrapper)
export type SDKControlRequestInner =
  | SDKControlInitializeRequest
  | SDKControlInterruptRequest
  | SDKControlPermissionRequest
  | SDKControlSetPermissionModeRequest
  | SDKControlSetModelRequest
  | SDKControlSetMaxThinkingTokensRequest
  | SDKControlMcpStatusRequest
  | SDKControlGetContextUsageRequest
  | SDKControlMcpSetServersRequest
  | SDKControlReloadPluginsRequest

// Inner union of all control response payload types (without wrapper)
export type SDKControlResponseInner =
  | SDKControlInitializeResponse
  | SDKControlMcpStatusResponse
  | SDKControlMcpSetServersResponse
  | SDKControlReloadPluginsResponse

// Outer wrapper types matching the wire format
// { type: 'control_request', request_id: string, request: SDKControlRequestInner }
export type SDKControlRequest = z.infer<ReturnType<typeof SDKControlRequestSchema>>

// { type: 'control_response', response: { subtype: 'success'|'error', request_id, ... } }
export type SDKControlResponse = z.infer<ReturnType<typeof SDKControlResponseSchema>>

// Stdout message type for structured output
import type { StdoutMessageSchema } from './controlSchemas.js'
export type StdoutMessage = z.infer<ReturnType<typeof StdoutMessageSchema>>
