/**
 * SDK Core Types (Generated) — TypeScript types inferred from coreSchemas.ts Zod schemas.
 *
 * This file would normally be auto-generated by `bun scripts/generate-sdk-types.ts`.
 * Manually reconstructed from schema definitions in coreSchemas.ts.
 */

import type { z } from 'zod/v4'
import type {
  ModelUsageSchema,
  ExitReasonSchema,
  HookEventSchema,
  HookInputSchema,
  HookJSONOutputSchema,
  PermissionModeSchema,
  PermissionResultSchema,
  PermissionUpdateSchema,
  SDKMessageSchema,
  SDKStatusSchema,
  SDKUserMessageSchema,
  SDKResultMessageSchema,
  SDKResultSuccessSchema,
  SDKResultErrorSchema,
  SDKSessionInfoSchema,
  SDKAssistantMessageSchema,
  SDKAssistantMessageErrorSchema,
  SDKCompactBoundaryMessageSchema,
  SDKPermissionDenialSchema,
  SDKUserMessageReplaySchema,
  SDKPostTurnSummaryMessageSchema,
  SDKStreamlinedTextMessageSchema,
  SDKStatusMessageSchema,
} from './coreSchemas.js'

export type ModelUsage = z.infer<ReturnType<typeof ModelUsageSchema>>
export type ExitReason = z.infer<ReturnType<typeof ExitReasonSchema>>
export type HookEvent = z.infer<ReturnType<typeof HookEventSchema>>
export type HookInput = z.infer<ReturnType<typeof HookInputSchema>>
export type HookJSONOutput = z.infer<ReturnType<typeof HookJSONOutputSchema>>
export type PermissionMode = z.infer<ReturnType<typeof PermissionModeSchema>>
export type PermissionResult = z.infer<ReturnType<typeof PermissionResultSchema>>
export type PermissionUpdate = z.infer<ReturnType<typeof PermissionUpdateSchema>>
export type SDKMessage = z.infer<ReturnType<typeof SDKMessageSchema>>
export type SDKStatus = z.infer<ReturnType<typeof SDKStatusSchema>>
export type SDKUserMessage = z.infer<ReturnType<typeof SDKUserMessageSchema>>
export type SDKResultMessage = z.infer<ReturnType<typeof SDKResultMessageSchema>>
export type SDKResultSuccess = z.infer<ReturnType<typeof SDKResultSuccessSchema>>
export type SDKResultError = z.infer<ReturnType<typeof SDKResultErrorSchema>>
export type SDKSessionInfo = z.infer<ReturnType<typeof SDKSessionInfoSchema>>
export type SDKAssistantMessage = z.infer<ReturnType<typeof SDKAssistantMessageSchema>>
export type SDKAssistantMessageError = z.infer<ReturnType<typeof SDKAssistantMessageErrorSchema>>
export type SDKCompactBoundaryMessage = z.infer<ReturnType<typeof SDKCompactBoundaryMessageSchema>>
export type SDKPermissionDenial = z.infer<ReturnType<typeof SDKPermissionDenialSchema>>
export type SDKUserMessageReplay = z.infer<ReturnType<typeof SDKUserMessageReplaySchema>>
export type SDKPostTurnSummaryMessage = z.infer<ReturnType<typeof SDKPostTurnSummaryMessageSchema>>
export type SDKStreamlinedTextMessage = z.infer<ReturnType<typeof SDKStreamlinedTextMessageSchema>>
export type SDKStatusMessage = z.infer<ReturnType<typeof SDKStatusMessageSchema>>
